// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDH0dzZC9dq35YDyt4nPUhcd_mwCXSqA',
    appId: '1:627973476127:web:0486f5845b4b3e84906a2a',
    messagingSenderId: '627973476127',
    projectId: 'real-estate-e676b',
    authDomain: 'real-estate-e676b.firebaseapp.com',
    storageBucket: 'real-estate-e676b.appspot.com',
    measurementId: 'G-P6E59N519Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBypGQnX5G1cPPZpUzxaS7Zp1YMxgT87bE',
    appId: '1:627973476127:android:59bcebc62b05ebb1906a2a',
    messagingSenderId: '627973476127',
    projectId: 'real-estate-e676b',
    storageBucket: 'real-estate-e676b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTLwiBzfoRguLXwM-e6N7pZ4bTkGvH1s',
    appId: '1:627973476127:ios:d93898237cc47a06906a2a',
    messagingSenderId: '627973476127',
    projectId: 'real-estate-e676b',
    storageBucket: 'real-estate-e676b.appspot.com',
    iosClientId: '627973476127-eehmg256s16ckvhpcsg051gjl56tmvv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfTLwiBzfoRguLXwM-e6N7pZ4bTkGvH1s',
    appId: '1:627973476127:ios:e6e372d6ba43e8b4906a2a',
    messagingSenderId: '627973476127',
    projectId: 'real-estate-e676b',
    storageBucket: 'real-estate-e676b.appspot.com',
    iosClientId: '627973476127-qpc6ml77lsdjir9g6p7ni5r30n9cel9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate.RunnerTests',
  );
}
